[project]
name = "blockchain-handle"
authors = ["Blockchain Handle Team"]
description = "A decentralized event feedback management platform"
telemetry = false
requirements = []
[contracts.blockchain-handle-core]
path = "contracts/blockchain-handle-core.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
